### ISSUE TITLE
Max resolution supported 

### ISSUE THREAD

**Issue by gyillikci** [AlainPaillou/JETSONSKY#2]
Alain Hello,

I would like to ask you about what would be the max resolution of zwo planetary camera that you would recommend? add on to this, fps is not the priority here. have you had any chance to observe which filters can do real time with which fps and resolution combination?

I am planning to buy asi294mm but, i ll revise it with your guide.

Best,

Happy holidays,

Giray

**Comment by AlainPaillou** [comment]
Hello,

well, the camera choice depends of a lot of things : the telescope, the targets, etc.

I did not realize ASI294MM gets a higher resolution than ASI294MC and a different ADC bit depth.

For sure, ASI294MM gets a very high resolution and this will be hard to manage.

This also depend of your computer. You will need a powerful one to get JetsonSky work properly with an ASI294MM camera for sure.

Considering my use (which can be different than yours), i would prefer an ASI533MM camera because photosites are bigger, full well is bigger, resolution is smaller but quite high and bit depth is 14 bits instead of 12.

In any case, i would recommend you to choose your camera depending of your needs. Do not choose the camera considering the software.

Alain

**Comment by gyillikci** [comment]
Hi,

I am planning to keep the camera and the lens as compact as possible. Components in my mind are Tokina 500mm or Tokina 900mm mirror lens to get the largest zoom in from the shortest possible barrel. To see the limits of this system, I was wondering to use very high-resolution camera like I mentioned before such as ASI294MM. 

Probably, not all filters that JetsonSky has would be applicable at once since the resolution would be very demanding on the hardware but, frame rate or resolution would be compromised.

This is kind of an experimental setup for observing the Sun and Moon in most of the case. I ll first start on my laptop with rtx2000 ada gpu. on top of that I ll combine jetson orin.

After your reply, I now consider to buy asi585mc or asi533mm along with asi294mm. 

Giray

**Comment by AlainPaillou** [comment]
Well, small photosites are suitable for high F/D ratio. With quite small F/D ratio (between 4 and 8 for example), larger photosite like 3.75um are better to avoir over sampling.

Do you have a motorized mount ? If not, long focal will be hard to use.

I think ASI295MM gets too much pixels.

An other problem : with monochrome sensor, you will have to use filters between lens and camera. At least IR-Cut filter because lens won't focus IR the same way they focus visible wavelength. It is hard to set filter between lens and camera because of the backfocus.

You will have to find an adapter to plug the camera on the lens and you won't have enough room to put a filter between them.

Considering all those things, it would be more safe for you to get a color camera. 

ASI585MC is quite good and less expensive than ASI533MC. But you will still have the IR focus distance problem. You will need an IR Cut filter, even with those cameras.

If you have a motorized mount, you could also consider to buy a Skywatcher 72ED telescope. It is quite small, quite light, quite good, not really expansive and you won't have the problems with adapter, room to put a 1"1/4 IR cut filter etc.

I know it is quite hard to choose a setup. Take your time. No hurry.

Alain

**Comment by gyillikci** [comment]
After your reply, I looked for the ASI533MC but couldn't find it in the US, so I bought the ASI585MM instead. I still plan to get the ASI533MM and ASI294MM one day.

I will use the AZ-GTi mount. With such a narrow field of view, any zoomed lens requires a mount. Anything less than 5 degrees necessitates a tripod to hold it steady.

It's worth learning about the necessity of an IR cut filter for monochrome cameras. I was completely unaware of this.

I found a Dörr Danubia mirror 500mm lens for 50 Euros. It's quite a good deal to at least get an idea, even if it doesn't fully meet my needs. If that happens, I will go with the Sky-Watcher 72ED.

**Comment by AlainPaillou** [comment]
I guest you mean the ASI585MC ? ASI585MM does not exist yet.

You will need an IRCut filter even with the ASI585MC.

I also have an AZ-GTi mount and it is a quite good mount.

Did you find an adapter to plug the lens on the camera ?

**Comment by gyillikci** [comment]
My apologies, it is asi585 with color sensor. 

The lens I purchased will include an additional T2 adaptor. I ll get t2-M42 adaptor additionally.  I do not anticipate significant issues in adapting the lens to the camera although, it is important to note that 
 these mounts can vary significantly between brands, and even within the same brand. But, I believe I ease out my way at this. 

Another lens I am considering purchasing is Walimex 500mm or 900mm, both of which featured with T2 mount. Additionally, some lenses come with their own filters.

Regarding the IR Cut filter, I am considering purchasing IR cut filter sheet and cut it on my needs. My first approach is not to have clearest picture but to experiment with general purpose reflector and catadioptric lenses.
